version: "3.9"
services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: sentiment-image:latest
    volumes:
      - ./src:/src
      - ./data:/data
      - ./model:/model
