version: "3.9"
services:
  main:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: sentiment-tokenizer
    volumes:
      - ./src:/src
      - ./data:/data
      - ./tokenizer:/tokenizer
      - ./model:/model
    command: bash docker-entrypoint.tokenizer.sh
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          capabilities: [gpu]